<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://doc.hyperf.io
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */

namespace HyperfTest\DB\Cases;

/**
 * @internal
 * @coversNothing
 */
class MySQLDriverTest extends PDODriverTest
{
    protected $driver = 'mysql';

    public function testFetch()
    {
        parent::testFetch(); // TODO: Change the autogenerated stub
    }

    public function testQuery()
    {
        parent::testQuery(); // TODO: Change the autogenerated stub
    }

    public function testInsertAndExecute()
    {
        parent::testInsertAndExecute(); // TODO: Change the autogenerated stub
    }

    public function testTransaction()
    {
        parent::testTransaction(); // TODO: Change the autogenerated stub
    }

    public function testConfig()
    {
        parent::testConfig(); // TODO: Change the autogenerated stub
    }

    public function testMultiTransaction()
    {
        parent::testMultiTransaction(); // TODO: Change the autogenerated stub
    }
}
