<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HealthCheck.proto

namespace Hyperf\ServiceGovernance\Grpc\Health;

if (false) {
    /**
     * This class is deprecated. Use Hyperf\ServiceGovernance\Grpc\Health\HealthCheckResponse\ServingStatus instead.
     * @deprecated
     */
    class HealthCheckResponse_ServingStatus {}
}
class_exists(HealthCheckResponse\ServingStatus::class);
@trigger_error('Hyperf\ServiceGovernance\Grpc\Health\HealthCheckResponse_ServingStatus is deprecated and will be removed in the next major release. Use Hyperf\ServiceGovernance\Grpc\Health\HealthCheckResponse\ServingStatus instead', E_USER_DEPRECATED);

