# These are supported funding model platforms

github: [huangzhhui, limingxinleo]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: #
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: #
otechie: # Replace with a single Otechie username
custom: https://www.hyperf.io/sponsor
