<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HealthCheck.proto

namespace Grpc\Health\V1;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Health\V1\HealthCheckResponse\ServingStatus instead.
     * @deprecated
     */
    class HealthCheckResponse_ServingStatus {}
}
class_exists(HealthCheckResponse\ServingStatus::class);
@trigger_error('Grpc\Health\V1\HealthCheckResponse_ServingStatus is deprecated and will be removed in the next major release. Use Grpc\Health\V1\HealthCheckResponse\ServingStatus instead', E_USER_DEPRECATED);

