<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://doc.hyperf.io
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf-cloud/hyperf/blob/master/LICENSE
 */

namespace HyperfTest\HttpServer\Stub;

class DispatcherFactory extends \Hyperf\HttpServer\Router\DispatcherFactory
{
    public function getPrefix(string $className, string $prefix): string
    {
        return parent::getPrefix($className, $prefix); // TODO: Change the autogenerated stub
    }
}
