<?php


namespace HyperfTest\HttpServer\Stub;


class DispatcherFactory extends \Hyperf\HttpServer\Router\DispatcherFactory
{
    public function getPrefix(string $className, string $prefix): string
    {
        return parent::getPrefix($className, $prefix); // TODO: Change the autogenerated stub
    }
}